import type { Metadata } from "next";
import Image from "next/image";
import { Navigation } from "@/components/ui/Navigation";
import { Footer } from "@/components/ui/Footer";
import { checkoutUrl } from "@/lib/catalog";

export const metadata: Metadata = { title: "AI Product Photography Playbook — 48 Examples + 120 Workflows", description: "An 84-page visual playbook with 48 AI product-photo examples, 120 editable workflows, correction prompts and a live prompt builder. USD 9.99.", alternates: { canonical: "/products/ai-product-photography-playbook" } };
const schema = { "@context": "https://schema.org", "@type": "Product", "@id": "https://velayon.com/products/ai-product-photography-playbook#product", name: "The AI Product Photography Playbook", description: "An 84-page visual playbook with 48 AI product-photo examples, 120 editable workflows, correction prompts and a live prompt builder.", category: "Digital product", url: "https://velayon.com/products/ai-product-photography-playbook", image: "https://velayon.com/products/ai-product-photography-playbook/book-3d.png", brand: { "@type": "Brand", name: "Velayon Dynamics" }, offers: { "@type": "Offer", url: "https://velayon.com/products/ai-product-photography-playbook", priceCurrency: "USD", price: "9.99", availability: "https://schema.org/InStock", seller: { "@id": "https://velayon.com/#organization" } } };

export default function ProductPage() {
  return <><Navigation /><main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <section className="product-hero"><div className="container product-hero-grid"><div className="product-hero-book"><span className="product-aura" /><span className="book-platform" /><Image src="/products/ai-product-photography-playbook/book-3d.png" alt="3D edition of The AI Product Photography Playbook" width={1103} height={1426} priority /></div><div className="product-hero-copy"><p className="eyebrow light">The complete visual prompt system</p><h1>Product images that look ready to sell.</h1><p>Stop guessing at vague prompts. Start from a visible result, adapt the commercial workflow and use focused correction steps when the image needs work.</p><div className="product-proof"><span>84-page PDF</span><span>48 premium examples</span><span>120 editable workflows</span><span>Prompt-builder workbook</span></div><div className="purchase-row"><strong>$9.99</strong><small>One-time purchase<br />Single-business licence</small></div><div className="action-row"><a className="button button-primary" href={checkoutUrl}>Buy Now <span>↗</span></a><a className="button button-ghost" href="#preview">Preview inside</a></div><p className="microcopy">The secure purchase enquiry opens on our contact page. When Paddle checkout is activated, it will be used only for this digital product.</p></div></div></section>
    <section className="section" id="preview"><div className="container"><header className="section-intro"><div><p className="eyebrow">See before you buy</p><h2>Result, prompt and repair step—together.</h2></div><p>The page design keeps the target image beside the production brief, so you can understand what each prompt is meant to achieve.</p></header><div className="preview-grid"><figure className="preview-wide"><div><Image src="/products/ai-product-photography-playbook/results-overview.png" alt="Twelve commercial product image results from the playbook" fill priority sizes="(max-width: 800px) 100vw, 66vw" /></div><figcaption><span>Results library</span>48 visual examples across twelve useful product categories.</figcaption></figure><figure><div><Image src="/products/ai-product-photography-playbook/prompt-result-preview.png" alt="Prompt and result paired inside the playbook" fill loading="eager" sizes="(max-width: 800px) 100vw, 33vw" /></div><figcaption><span>Working pages</span>Prompt structure beside the result it is designed to create.</figcaption></figure><figure><div><Image src="/products/ai-product-photography-playbook/prompt-builder-preview.png" alt="Editable product photography prompt builder" fill loading="eager" sizes="(max-width: 800px) 100vw, 33vw" /></div><figcaption><span>Editable builder</span>Assemble a new brief from product, scene, light and constraints.</figcaption></figure></div></div></section>
    <section className="section soft-section"><div className="container"><header className="section-intro compact"><div><p className="eyebrow">What you receive</p><h2>A complete production kit.</h2></div></header><div className="feature-card-grid">{[["▤", "Visual playbook", "84 pages covering composition, lighting, material realism and commercial review."], ["◫", "Results library", "48 examples spanning packshots, social, food, beauty, fashion, home and more."], ["⌁", "Workflow library", "120 searchable prompts for categories, placements and campaign needs."], ["＋", "Prompt builder", "An editable workbook for constructing consistent production briefs."], ["↻", "Correction system", "Targeted repair prompts that preserve the parts of the image already working."], ["✓", "Quality control", "Quick-start guidance, campaign recipes and a commercial review scorecard."]].map(([icon,t,c]) => <article className="feature-card" key={t}><span className="feature-card-icon">{icon}</span><div><h3>{t}</h3><p>{c}</p></div></article>)}</div></div></section>
    <section className="licence-section"><div className="container licence-grid"><div><p className="eyebrow light">Clear commercial use</p><h2>Use it to create for one business.</h2></div><div><ul><li>Adapt every workflow to your own products and campaigns.</li><li>Use generated images commercially, subject to your image tool and underlying rights.</li><li>Keep the playbook, workbook and source files inside your licensed business.</li></ul><a className="button button-primary" href={checkoutUrl}>Buy the playbook for $9.99 <span>↗</span></a></div></div></section>
  </main><Footer /></>;
}
