import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Navigation } from "@/components/ui/Navigation";
import { Footer } from "@/components/ui/Footer";

export const metadata: Metadata = { title: "About Velayon Dynamics — Nepal Digital Products & Software Studio", description: "Learn about Velayon Dynamics, the Nepal-based digital products and software studio founded by Bibek Kumar Thagunna to make useful technology clearer to understand and easier to buy.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <><Navigation /><main>
    <section className="about-hero"><div className="container about-hero-inner"><p className="eyebrow light">About Velayon Dynamics</p><h1>A small studio with a practical point of view.</h1><p>Velayon Dynamics creates original digital products and clearly scoped software for people who want to move from an idea to something useful, credible and ready to launch.</p></div></section>
    <section className="section founder-section"><div className="container founder-grid"><div className="founder-portrait-wrap"><div className="founder-portrait"><Image src="/brand/bibek-kumar-thagunna-portrait-v1.png" alt="Bibek Kumar Thagunna, founder of Velayon Dynamics" width={1101} height={1429} /></div><span>Founder · Designer · Developer</span></div><div className="founder-copy"><p className="eyebrow">Meet the founder</p><h2>Bibek Kumar Thagunna</h2><p className="founder-lead">I started Velayon Dynamics to make digital work easier to understand and easier to buy.</p><p>That means products with real previews, service packages with visible deliverables and development conversations focused on the result—not a wall of technical language.</p><p>From Nepal, I work with customers remotely to design and build focused websites, Flutter and Expo apps, native Android products and practical creative systems.</p><div className="founder-links"><Link href="/about/bibek-kumar-thagunna">Read Bibek’s profile ↗</Link><Link href="/contact">contact@velayon.com ↗</Link></div></div></div></section>
    <section className="section standard-section"><div className="container"><header className="section-intro"><div><p className="eyebrow">The Velayon Dynamics standard</p><h2>Principles you can feel in the finished work.</h2></div><p>A few simple rules guide the product, the process and the handover.</p></header><div className="standard-grid">{[["Clear","Clear before clever","The scope, price and next action should be understandable without a sales call."],["Useful","Useful before decorative","Design decisions must support trust, comprehension and the task a customer came to complete."],["Focused","Focused before oversized","A smaller release that works is more valuable than a long feature list that never launches."],["Owned","Owned by the customer","Files, documentation and handover should leave the customer in control of what was built."]].map(([label,t,c]) => <article className="standard-card" key={label}><span>{label}</span><h3>{t}</h3><p>{c}</p><i aria-hidden="true">—</i></article>)}</div></div></section>
  </main><Footer /></>;
}
