import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Navigation } from "@/components/ui/Navigation";
import { Footer } from "@/components/ui/Footer";
import { websitePackages } from "@/lib/catalog";

export const metadata: Metadata = { title: "Website Design & Development Packages", description: "Clearly scoped website packages for landing pages, service businesses, booking-led companies and online stores. Packages from USD 599.", alternates: { canonical: "/services/websites" } };
const schema = { "@context": "https://schema.org", "@type": "Service", name: "Website Design and Development", provider: { "@type": "Organization", name: "Velayon" }, areaServed: "Worldwide" };

export default function WebsitesPage() {
  return <><Navigation /><main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <section className="service-hero"><div className="container service-hero-grid"><div className="service-hero-copy"><p className="eyebrow">Website design & development</p><h1>A website that earns trust before the first conversation.</h1><p>Choose by business outcome, then see the pages, launch essentials, delivery window and investment before work begins.</p><div className="service-facts"><span><b>From $599</b> published package pricing</span><span><b>7 days–6 weeks</b> typical delivery</span><span><b>Worldwide</b> remote collaboration</span></div><Link className="button button-dark" href="#packages">Compare website packages <span>↓</span></Link></div><div className="service-hero-media"><Image src="/brand/website-packages-v2.webp" alt="Responsive Velayon website design displayed on a laptop" fill priority sizes="(max-width: 900px) 100vw, 48vw" /></div></div></section>
    <section className="section" id="packages"><div className="container"><header className="section-intro"><div><p className="eyebrow">Packages by business need</p><h2>Pick the closest outcome.</h2></div><p>These are complete starting scopes—not hourly estimates. Extra pages, integrations or specialist features are itemised before you approve them.</p></header><div className="package-grid">{websitePackages.map((item, index) => <article className={`service-card ${item.featured ? "featured" : ""}`} key={item.name}>{item.featured && <span className="service-badge">Most requested</span>}<p className="card-number">0{index + 1}</p><h3>{item.name}</h3><p className="service-fit">{item.fit}</p><div className="service-price"><strong>{item.price}</strong><span>{item.timeline}</span></div><ul>{item.features.map((feature) => <li key={feature}>{feature}</li>)}</ul><Link className="button button-outline" href={`/contact?project=${encodeURIComponent(item.name)}`}>Discuss this package <span>↗</span></Link></article>)}</div><div className="scope-bar"><strong>Need a different combination?</strong><p>Begin with the closest package. Languages, memberships, advanced search, extra integrations and ongoing support can be scoped separately.</p><Link href="/contact">Ask about a custom scope ↗</Link></div></div></section>
    <section className="section dark-section"><div className="container"><header className="section-intro compact"><div><p className="eyebrow light">Included in every build</p><h2>Professional foundations are part of the work.</h2></div></header><div className="deliverable-grid dark-cards">{[["01","Visual direction","A coherent interface shaped around your brand, audience and offer."],["02","Responsive build","Purposeful phone, tablet and desktop layouts—not a squeezed desktop page."],["03","SEO foundation","Semantic pages, useful metadata, sitemap, robots rules and internal links."],["04","Performance review","Image, layout and frontend checks before the site is handed over."],["05","Measurement setup","Connection to your preferred analytics tool for visits and conversions."],["06","Documented handover","Deployment support, ownership transfer and concise operating guidance."]].map(([n,t,c]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></div></section>
    <section className="closing-cta"><div className="container closing-cta-grid"><div><p className="eyebrow light">Have a website in mind?</p><h2>Start with the outcome. We will make the scope clear.</h2></div><div><p>Share the audience, the main action and any systems the site needs to connect to.</p><Link className="button button-primary" href="/contact">Discuss your website <span>↗</span></Link></div></div></section>
  </main><Footer /></>;
}
