import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Navigation } from "@/components/ui/Navigation";
import { Footer } from "@/components/ui/Footer";
import { websitePackages } from "@/lib/catalog";

export const metadata: Metadata = { title: "Website Design & Development in Nepal | Packages from $599", description: "Responsive website design and development by Velayon Dynamics in Nepal for businesses worldwide. Clearly scoped landing pages, business sites, booking websites and ecommerce builds from USD 599.", alternates: { canonical: "/services/websites" } };
const schema = { "@context": "https://schema.org", "@type": "Service", "@id": "https://velayon.com/services/websites#service", name: "Website Design and Development", serviceType: "Responsive website design and development", url: "https://velayon.com/services/websites", provider: { "@id": "https://velayon.com/#organization" }, areaServed: [{ "@type": "Country", name: "Nepal" }, "Worldwide"], offers: { "@type": "AggregateOffer", priceCurrency: "USD", lowPrice: "599", offerCount: websitePackages.length } };

export default function WebsitesPage() {
  return <><Navigation /><main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <section className="service-hero"><div className="container service-hero-grid"><div className="service-hero-copy"><p className="eyebrow">Website design & development</p><h1>A website that earns trust before the first conversation.</h1><p>Choose by business outcome, then see the pages, launch essentials, delivery window and investment before work begins.</p><div className="service-facts"><span><b>From $599</b> published package pricing</span><span><b>7 days–6 weeks</b> typical delivery</span><span><b>Worldwide</b> remote collaboration</span></div><Link className="button button-dark" href="#packages">Compare website packages <span>↓</span></Link></div><div className="service-hero-media device-stage laptop-stage"><Image src="/brand/website-laptop-3d-v2.webp" alt="Three-dimensional laptop angled left and showing a Velayon website" width={1536} height={1024} priority fetchPriority="high" sizes="(max-width: 900px) 100vw, 54vw" /></div></div></section>
    <section className="section" id="packages"><div className="container"><header className="section-intro"><div><p className="eyebrow">Packages by business need</p><h2>Pick the closest outcome.</h2></div><p>These are complete starting scopes—not hourly estimates. Extra pages, integrations or specialist features are itemised before you approve them.</p></header><div className="package-grid">{websitePackages.map((item, index) => <article className={`service-card ${item.featured ? "featured" : ""}`} key={item.name}>{item.featured && <span className="service-badge">Most requested</span>}<p className="card-number">0{index + 1}</p><h3>{item.name}</h3><p className="service-fit">{item.fit}</p><div className="service-price"><strong>{item.price}</strong><span>{item.timeline}</span></div><ul>{item.features.map((feature) => <li key={feature}>{feature}</li>)}</ul><Link className="button button-outline" href={`/contact?project=${encodeURIComponent(item.name)}`}>Discuss this package <span>↗</span></Link></article>)}</div><div className="scope-bar"><strong>Need a different combination?</strong><p>Begin with the closest package. Languages, memberships, advanced search, extra integrations and ongoing support can be scoped separately.</p><Link href="/contact">Ask about a custom scope ↗</Link></div></div></section>
    <section className="section foundation-section"><div className="container"><header className="section-intro"><div><p className="eyebrow">Included in every build</p><h2>Professional foundations, already included.</h2></div><p>These are not upgrades added after the estimate. They are the baseline for a credible, maintainable website.</p></header><div className="foundation-grid">{[["Art direction","Visual direction","A coherent interface shaped around your brand, audience and offer."],["Every screen","Responsive build","Purposeful phone, tablet and desktop layouts—not a squeezed desktop page."],["Discoverable","SEO foundation","Semantic pages, useful metadata, sitemap, robots rules and internal links."],["Fast by default","Performance review","Image, layout and frontend checks before the site is handed over."],["Measurable","Analytics setup","Connection to your preferred analytics tool for visits and conversions."],["Yours to run","Documented handover","Deployment support, ownership transfer and concise operating guidance."]].map(([label,t,c]) => <article className="foundation-card" key={t}><span>{label}</span><h3>{t}</h3><p>{c}</p><i aria-hidden="true">↗</i></article>)}</div></div></section>
  </main><Footer /></>;
}
