import type { Metadata } from "next";
import { Navigation } from "@/components/ui/Navigation";
import { Footer } from "@/components/ui/Footer";

export const metadata: Metadata = { title: "Terms of Use and Sale", description: "Terms for Velayon digital products and clearly scoped development services.", alternates: { canonical: "/terms" } };

export default function TermsPage() {
  return <><Navigation /><main className="policy-page"><article className="container"><p className="eyebrow blue">Effective September 28, 2026</p><h1 className="serif">Terms of use and sale</h1><p>These terms apply to velayon.com, Velayon digital products and development services. A service proposal, statement of work or product licence may add more specific terms and will control where it differs from this page.</p><h2>Digital products</h2><p>Digital files are licensed, not sold as intellectual property. Buyers may use them only within the licence supplied with the product. Source files may not be shared, resold, sublicensed or presented as a competing product.</p><h2>Development services</h2><p>Published package pricing applies to the listed scope. Work begins after the scope, schedule, payment milestones and responsibilities are confirmed in writing. Additional work requires an agreed change or separate estimate.</p><h2>Third-party costs</h2><p>Domains, hosting, app-store charges, paid software, plugins, subscriptions, transaction fees and third-party services are not included unless a written proposal says otherwise.</p><h2>Results and dependencies</h2><p>Velayon does not promise particular revenue, search ranking, conversion rate or business performance. Delivery dates may depend on timely client feedback, content, access and third-party approvals.</p><h2>Support and problems</h2><p>If a file is damaged, missing or delivered incorrectly, contact us so we can correct the issue. Any refund right required by applicable law remains unaffected.</p><h2>Contact</h2><p>Questions about these terms can be sent to <a href="mailto:contact@velayon.com">contact@velayon.com</a>.</p></article></main><Footer /></>;
}
