import type { Metadata } from "next";
import { Navigation } from "@/components/ui/Navigation";
import { Footer } from "@/components/ui/Footer";
import Link from "next/link";

export const metadata: Metadata = { title: "Terms of Use and Sale", description: "Terms for Velayon Dynamics digital products and clearly scoped development services.", alternates: { canonical: "/terms" } };

export default function TermsPage() {
  return <><Navigation /><main className="policy-page"><article className="container"><p className="eyebrow blue">Effective September 29, 2026</p><h1>Terms of use and sale</h1><p>These terms apply to velayon.com, original digital products published by Velayon Dynamics and development services provided under the Velayon Dynamics name. Velayon Dynamics is the trading name used by founder Bibek Kumar Thagunna in Nepal. A product licence, service proposal or statement of work may add more specific terms and will control where it differs from this page.</p><h2>Digital products</h2><p>Digital files are licensed, not sold as intellectual property. Buyers may use them only within the licence supplied with the product. Source files may not be shared, resold, sublicensed or presented as a competing product. Each product page states the price, format, included files, licence summary and delivery method before purchase.</p><h2>Payment processing</h2><p>When Paddle checkout is available, Paddle acts as merchant of record only for the digital products clearly identified on their product pages. Custom website and mobile-development services are contracted and invoiced separately; they are not purchased through a digital-product checkout.</p><h2>Development services</h2><p>Published package pricing applies to the listed scope. Work begins after the scope, schedule, payment milestones and responsibilities are confirmed in writing. Additional work requires an agreed change or separate estimate.</p><h2>Third-party costs</h2><p>Domains, hosting, app-store charges, paid software, plugins, subscriptions, transaction fees and third-party services are not included unless a written proposal says otherwise.</p><h2>Results and dependencies</h2><p>Velayon Dynamics does not promise particular revenue, search ranking, conversion rate or business performance. Delivery dates may depend on timely client feedback, content, access and third-party approvals.</p><h2>Refunds and support</h2><p>Refund handling is explained in our <Link href="/refund-policy">Refund Policy</Link>. If a file is damaged, missing or delivered incorrectly, use the <Link href="/contact">contact page</Link> so we can investigate and correct the issue. Mandatory consumer rights remain unaffected.</p><h2>Contact</h2><p>Questions about these terms can be submitted through the <Link href="/contact">Velayon Dynamics contact page</Link>.</p></article></main><Footer /></>;
}
