import type { Metadata } from "next";
import { Navigation } from "@/components/ui/Navigation";
import { Footer } from "@/components/ui/Footer";
import Link from "next/link";

export const metadata: Metadata = { title: "Privacy Policy", description: "How Velayon Dynamics handles information submitted through velayon.com.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <><Navigation /><main className="policy-page"><article className="container"><p className="eyebrow blue">Effective September 29, 2026</p><h1>Privacy policy</h1><p>Velayon Dynamics collects only the information needed to respond to enquiries, provide contracted work, support buyers and deliver digital products.</p><h2>Information we may receive</h2><p>The secure enquiry form may send your name, email address, company, selected package, budget range, timeline, technology preferences and project description through Web3Forms to the Velayon Dynamics inbox. A payment provider may separately process billing, tax and transaction information when checkout is enabled.</p><h2>How information is used</h2><p>We use information to respond to enquiries, fulfil purchases, deliver contracted work, provide support, keep necessary business records, prevent abuse and protect the security of our services.</p><h2>Service providers</h2><p>Hosting, form-delivery, analytics, email and payment providers may process limited information under their own privacy terms. Velayon Dynamics does not sell personal information.</p><h2>Retention and requests</h2><p>Information is retained only as long as reasonably needed for delivery, legal, tax and security purposes. To request access, correction or deletion, use the <Link href="/contact">contact page</Link>.</p><h2>International processing</h2><p>Velayon Dynamics operates from Nepal and works internationally. Service providers may process information in other countries subject to their safeguards and applicable law.</p><h2>Updates</h2><p>This policy may be updated when website features or providers change. The effective date above identifies the current version.</p></article></main><Footer /></>;
}
